name: Golang / Security

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  golang-security-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: "."
